stages:
  - lint
  - build
  - test

# Global variables and cache
variables:
  GRADLE_USER_HOME: "${CI_PROJECT_DIR}/.gradle"
  BACKEND_IMAGE_NAME: backend
  ANDROID_IMAGE_NAME: android

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .gradle/
    - app/lint/reports/
    - app/build/
    - backend/node_modules/
    - ./build.gradle.kts

before_script:
  - chmod +x ./gradlew

# Android-specific jobs
lintAndroidDebug:
  stage: lint
  image: alvrme/alpine-android:android-34-jdk17
  script:
    - ./gradlew -Pci --console=plain :app:lintDebug
  artifacts:
    paths:
      - app/build/lint/reports/lint-results-debug.xml
  only:
    - main
    - merge_requests
  tags:
    - hva

assembleAndroidDebug:
  stage: build
  image: alvrme/alpine-android:android-34-jdk17
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs
  only:
    - main
    - merge_requests
  tags:
    - hva

testAndroidDebug:
  stage: test
  image: alvrme/alpine-android:android-34-jdk17
  script:
    - ./gradlew -Pci --console=plain :app:testDebug
  artifacts:
    when: always
    paths:
      - app/build/reports/tests/
  only:
    - main
    - merge_requests
  tags:
    - hva

# Backend-specific jobs
lintBackend:
  stage: lint
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - echo "Linting backend code..."
    - docker build --target=lint -t ${BACKEND_IMAGE_NAME}-lint .
    - echo "No lint issues found in backend."
  only:
    refs:
      - main
      - merge_requests
    changes:
      - backend/**/*
  tags:
    - hva